name: build

on:
  release:
    types:
      - published
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Update version
        if: ${{ github.event_name == 'release' }}
        run: npm version --no-git-tag-version ${{ github.ref_name }}

      - name: NPM install
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Package vscode extension
        run: npm run package

      - name: Publish to marketplace
        if: ${{ github.event_name == 'release' }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm run deploy
